# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

import Myclass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1110, 810))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("border: none;")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(-1, 0, 11, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 155, 378))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setMinimumHeight(25)  # 调整高度为30
        self.verticalLayout.addWidget(self.comboBox_2)
        self.treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents_6)
        self.treeView.setStyleSheet("border: none;")
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget)
        self.scrollArea_2.setStyleSheet("border: none;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 155, 390))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView_3 = QtWidgets.QTreeView(self.scrollAreaWidgetContents_9)
        self.treeView_3.setStyleSheet("border: none;")
        self.treeView_3.setObjectName("treeView_3")
        self.verticalLayout_2.addWidget(self.treeView_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.horizontalLayout.addWidget(self.widget)


        self.graphicsSence = Myclass.GraphicScene(parent=self.centralwidget)
        self.graphicsView = Myclass.GraphicView(parent=self.centralwidget, graphic_scene=self.graphicsSence)


        self.graphicsView.setMinimumSize(QtCore.QSize(660, 610))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.setStyleSheet("border: none;")
        self.horizontalLayout.addWidget(self.graphicsView)


        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea_3.setStyleSheet("border: none;")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 155, 764))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_10)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setMinimumHeight(25)  # 调整高度为30
        self.verticalLayout_4.addWidget(self.comboBox)


        self.treeView_kg = Myclass.my_treeview(parent=self.scrollAreaWidgetContents_10,scence=self.graphicsSence)
        self.treeView_kg.setStyleSheet("border: none;")
        self.treeView_kg.setObjectName("treeView_kg")
        self.verticalLayout_4.addWidget(self.treeView_kg)




        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_10)
        self.verticalLayout_5.addWidget(self.scrollArea_3)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action1_1 = QtWidgets.QAction(MainWindow)
        self.action1_1.setObjectName("action1_1")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action2_1 = QtWidgets.QAction(MainWindow)
        self.action2_1.setObjectName("action2_1")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action2_3 = QtWidgets.QAction(MainWindow)
        self.action2_3.setObjectName("action2_3")
        self.menu.addAction(self.action1_1)
        self.menu.addAction(self.action1_2)
        self.menu_2.addAction(self.action2_1)
        self.menu_2.addAction(self.action2_2)
        self.menu_2.addAction(self.action2_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.action1_1)
        self.toolBar.addAction(self.action1_2)
        self.toolBar.addAction(self.action2_1)
        self.toolBar.addAction(self.action2_2)
        self.toolBar.addAction(self.action2_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action1_1.setText(_translate("MainWindow", "新建图谱"))
        self.action1_2.setText(_translate("MainWindow", "保存"))
        self.action2_1.setText(_translate("MainWindow", "自动布局"))
        self.action2_2.setText(_translate("MainWindow", "复制知识图谱"))
        self.action2_3.setText(_translate("MainWindow", "鼠标"))
